name: auto merge PRs

on:
  pull_request_review:
    types:
      - submitted

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/merge-pull-requests
      - name: automerge
        uses: 'pascalgn/automerge-action@v0.13.0'
        env:
          MERGE_LABELS: ''
          MERGE_METHOD: 'rebase'
          MERGE_COMMIT_MESSAGE: 'pull-request-title'
          MERGE_DELETE_BRANCH: true
          UPDATE_LABELS: ''
          UPDATE_METHOD: 'merge'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
